services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=pymarket_db
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-data: